import { GemstoneRecord } from '@/types/gemstone.types';

export const GEMSTONE_TYPES = [
  'Sapphire',
  'Ruby',
  'Emerald',
  'Spinel',
  'Alexandrite',
  'Tanzanite',
  'Tourmaline',
  'Garnet',
  'Aquamarine',
  'Topaz',
  'Chrysoberyl',
  'Zircon',
] as const;

export const GEMSTONE_VARIETIES = [
  'Blue Sapphire',
  'Padparadscha Sapphire',
  'Pink Sapphire',
  'Yellow Sapphire',
  'Green Sapphire',
  'White Sapphire',
  'Pigeon Blood Ruby',
  'Star Ruby',
  'Tsavorite Garnet',
  'Spessartite Garnet',
  'Rubellite Tourmaline',
  'Verdelite Tourmaline',
  'Indicolite Tourmaline',
  'Paraiba Tourmaline',
  'Alexandrite',
  'Cobalt Spinel',
  'Custom / Other',
] as const;

export const TREATMENT_OPTIONS = [
  'None / Unheated',
  'Heat Treated',
  'Beryllium Treated',
  'Fissure Filled / Oiled',
  'Irradiated',
  'Diffusion Treated',
  'Surface Coated',
  'Unknown',
] as const;

export const ORIGIN_OPTIONS = [
  'Madagascar (Ilakaka)',
  'Madagascar (Andranondambo)',
  'Madagascar (Didy)',
  'Sri Lanka (Ratnapura)',
  'Myanmar (Mogok)',
  'Kashmir (India)',
  'Tanzania (Tunduru)',
  'Tanzania (Merelani)',
  'Colombia (Muzo)',
  'Mozambique (Montepuez)',
  'Brazil (Minas Gerais)',
  'Thailand (Chanthaburi)',
  'Australia',
  'Unknown / Unspecified',
] as const;

export const WEIGHT_UNITS = [
  'ct', // Carat
  'g',  // Gram
  'ratti',
] as const;

export const SHAPE_OPTIONS = [
  'Cushion',
  'Oval',
  'Round Brilliant',
  'Emerald Cut',
  'Pear',
  'Marquise',
  'Princess',
  'Radiant',
  'Heart',
  'Octagon',
  'Trillion',
  'Sugarloaf',
  'Cabochon',
] as const;

export const CUT_OPTIONS = [
  'Excellent',
  'Very Good',
  'Good',
  'Fair',
  'Step Cut',
  'Brilliant Cut',
  'Mixed Cut',
  'Checkerboard Cut',
  'Cabochon',
] as const;

export const COLOR_OPTIONS = [
  'Cornflower Blue',
  'Royal Blue',
  'Deep Velvet Blue',
  'Pigeon Blood Red',
  'Padparadscha (Pinkish-Orange)',
  'Vivid Pink',
  'Pastel Pink',
  'Vivid Canary Yellow',
  'Vivid Emerald Green',
  'Teal / Peacock',
  'Vivid Violet',
  'Color Change (Teal to Purple)',
] as const;

export const CLARITY_OPTIONS = [
  'FL / IF (Flawless / Internally Flawless)',
  'VVS1 (Very Very Slightly Included 1)',
  'VVS2 (Very Very Slightly Included 2)',
  'VS1 (Very Slightly Included 1)',
  'VS2 (Very Slightly Included 2)',
  'SI1 (Slightly Included 1)',
  'SI2 (Slightly Included 2)',
  'Eye Clean',
  'Moderately Included',
] as const;

export const CERTIFICATION_LABS = [
  'GIA (Gemological Institute of America)',
  'GRS (GemResearch Swisslab)',
  'SSEF (Swiss Gemmological Institute)',
  'Gübelin Gem Lab',
  'IGI (International Gemological Institute)',
  'CGL (Ceylon Gem Laboratory)',
  'AIGS (Asian Institute of Gemological Sciences)',
  'Self-Certified / In-house',
  'Uncertified',
] as const;

export const INITIAL_DUMMY_GEMSTONES: GemstoneRecord[] = [
  {
    id: 'gem-101',
    serialNo: 'GT-MAD-2026-001',
    type: 'Sapphire',
    variety: 'Blue Sapphire',
    nature: 'Natural',
    treatment: 'None / Unheated',
    origin: 'Madagascar (Ilakaka)',
    quantity: 1,
    weight: 4.85,
    weightUnit: 'ct',
    shape: 'Cushion',
    cut: 'Excellent',
    color: 'Royal Blue',
    clarity: 'VVS1 (Very Very Slightly Included 1)',
    dimensions: '9.4 x 7.8 x 5.2 mm',
    certificationNo: 'GIA-24819031',
    certificationLab: 'GIA (Gemological Institute of America)',
    createdAt: '2026-08-01T10:30:00Z',
  },
  {
    id: 'gem-102',
    serialNo: 'GT-MAD-2026-002',
    type: 'Ruby',
    variety: 'Pigeon Blood Ruby',
    nature: 'Natural',
    treatment: 'Heat Treated',
    origin: 'Mozambique (Montepuez)',
    quantity: 1,
    weight: 3.12,
    weightUnit: 'ct',
    shape: 'Oval',
    cut: 'Very Good',
    color: 'Pigeon Blood Red',
    clarity: 'VS1 (Very Slightly Included 1)',
    dimensions: '8.1 x 6.4 x 4.0 mm',
    certificationNo: 'GRS-2025-0948',
    certificationLab: 'GRS (GemResearch Swisslab)',
    createdAt: '2026-08-03T14:15:00Z',
  },
  {
    id: 'gem-103',
    serialNo: 'GT-MAD-2026-003',
    type: 'Sapphire',
    variety: 'Padparadscha Sapphire',
    nature: 'Natural',
    treatment: 'None / Unheated',
    origin: 'Sri Lanka (Ratnapura)',
    quantity: 1,
    weight: 2.75,
    weightUnit: 'ct',
    shape: 'Pear',
    cut: 'Excellent',
    color: 'Padparadscha (Pinkish-Orange)',
    clarity: 'VVS2 (Very Very Slightly Included 2)',
    dimensions: '8.8 x 6.0 x 3.9 mm',
    certificationNo: 'SSEF-118942',
    certificationLab: 'SSEF (Swiss Gemmological Institute)',
    createdAt: '2026-08-05T09:45:00Z',
  },
  {
    id: 'gem-104',
    serialNo: 'GT-MAD-2026-004',
    type: 'Emerald',
    variety: 'Tsavorite Garnet',
    nature: 'Natural',
    treatment: 'None / Unheated',
    origin: 'Madagascar (Didy)',
    quantity: 2,
    weight: 5.40,
    weightUnit: 'ct',
    shape: 'Emerald Cut',
    cut: 'Step Cut',
    color: 'Vivid Emerald Green',
    clarity: 'Eye Clean',
    dimensions: '7.5 x 5.5 x 4.2 mm',
    certificationNo: 'GUB-2026-7811',
    certificationLab: 'Gübelin Gem Lab',
    createdAt: '2026-08-07T11:20:00Z',
  },
  {
    id: 'gem-105',
    serialNo: 'GT-MAD-2026-005',
    type: 'Spinel',
    variety: 'Cobalt Spinel',
    nature: 'Natural',
    treatment: 'None / Unheated',
    origin: 'Madagascar (Andranondambo)',
    quantity: 1,
    weight: 1.95,
    weightUnit: 'ct',
    shape: 'Round Brilliant',
    cut: 'Brilliant Cut',
    color: 'Teal / Peacock',
    clarity: 'FL / IF (Flawless / Internally Flawless)',
    dimensions: '6.8 x 6.8 x 4.1 mm',
    certificationNo: 'GIA-64901238',
    certificationLab: 'GIA (Gemological Institute of America)',
    createdAt: '2026-08-08T16:00:00Z',
  },
  {
    id: 'gem-106',
    serialNo: 'GT-SYN-2026-006',
    type: 'Alexandrite',
    variety: 'Alexandrite',
    nature: 'Synthetic',
    treatment: 'None / Unheated',
    origin: 'Unknown / Unspecified',
    quantity: 4,
    weight: 8.20,
    weightUnit: 'ct',
    shape: 'Cushion',
    cut: 'Mixed Cut',
    color: 'Color Change (Teal to Purple)',
    clarity: 'Eye Clean',
    dimensions: '7.0 x 7.0 x 4.5 mm',
    certificationNo: 'INHOUSE-SYN-04',
    certificationLab: 'Self-Certified / In-house',
    createdAt: '2026-08-09T13:10:00Z',
  },
];
