import type { Role } from '@/constants/roles';

/* ── Collection Type ──────────────────────────────────────────────────────── */

export type CollectionType = 'single_stone' | 'bulk_stones' | 'jewellery' | 'industrial_stones';

/* ── Collection Status ────────────────────────────────────────────────────── */

export type CollectionStatus = 'review' | 'accepted';

/* ── Payment Method ───────────────────────────────────────────────────────── */

export type PaymentMethod = 'cash' | 'mobile_money' | 'bank_transfer';

/* ── User reference (seller, creator, approver) ──────────────────────────── */

export interface UserRef {
  id: string;
  first_name: string;
  last_name?: string;
  email: string;
  role: Role;
}

/** @deprecated Use UserRef — kept for backward compatibility */
export type SellerRef = UserRef;

export interface SellerResponseRef {
  data: UserRef[];
}

/* ── Bulk stone row ───────────────────────────────────────────────────────── */

export interface BulkStoneRow {
  gemstone_type: string;
  variety: string;
  quantity: number;
  weight: number;
  weight_unit: string;
}

/* ── Collection Records (API response shape) ──────────────────────────────── */

interface CollectionBase {
  id: string;
  serial_no: string;                     // auto-generated by backend
  collection_type: CollectionType;
  seller_id: string;
  seller: UserRef;                       // embedded seller reference
  certification_no: string;
  certification_lab: string;
  asking_price: number;
  image_urls: string[];                  // backend-managed image URLs
  certificate_url?: string | null;       // optional single certificate (image or PDF)
  status: CollectionStatus;             // 'review' on creation; 'accepted' after approval
  finalized_price?: number | null;      // set on acceptance
  payment_method?: PaymentMethod | null; // set on acceptance
  barcode_url?: string | null;          // generated by backend on acceptance
  voucher_url?: string | null;          // payment voucher PDF, generated on acceptance
  created_by?: UserRef | null;          // user who created the collection record
  approved_by?: UserRef | null;         // admin/manager who accepted the collection
  approved_at?: string | null;          // ISO timestamp of acceptance
  created_at: string;
  updated_at: string;
}

export interface SingleStoneCollection extends CollectionBase {
  collection_type: 'single_stone';
  gemstone_type: string;
  variety: string;
  treatment: string;
  origin: string;
  weight: number;
  weight_unit: string;
  shape: string;
  cut: string;
  color: string;
  clarity: string;
  dimensions: string;
}

export interface BulkStonesCollection extends CollectionBase {
  collection_type: 'bulk_stones';
  stones: BulkStoneRow[];
  description: string;
}

export interface JewelleryCollection extends CollectionBase {
  collection_type: 'jewellery';
  weight: number;
  weight_unit: string;
  description: string;
}

export interface IndustrialStonesCollection extends CollectionBase {
  collection_type: 'industrial_stones';
  stone_type: string;
  variety: string;
  weight: number;
  weight_unit: string;
  description: string;
}

export type CollectionRecord =
  | SingleStoneCollection
  | BulkStonesCollection
  | JewelleryCollection
  | IndustrialStonesCollection;

/* ── Form Data (drawer state shape) ──────────────────────────────────────── */
// Values come from constants key-value pairs; submitted as their `value` string.
// Submitted to the API as multipart/form-data via the service layer.

interface CollectionFormBase {
  collection_type: CollectionType;
  seller_id: string;
  certification_no: string;
  certification_lab: string;           // free-text or value from CERTIFICATION_LABS constant
  asking_price: number;
  images: File[];                       // newly added image files
  removed_image_urls: string[];         // existing image URLs to delete on update
  certificate?: File | null;            // optional new certificate file (image or PDF)
  remove_certificate?: boolean;         // true = delete the existing certificate on update
}

export interface SingleStoneFormData extends CollectionFormBase {
  collection_type: 'single_stone';
  gemstone_type: string;               // value from GEMSTONE_TYPES constant
  variety: string;
  treatment: string;                   // value from TREATMENT_OPTIONS constant
  origin: string;                      // value from ORIGIN_OPTIONS constant
  weight: number;
  weight_unit: string;                 // value from WEIGHT_UNITS constant
  shape: string;                       // value from SHAPE_OPTIONS constant
  cut: string;                         // value from CUT_OPTIONS constant
  color: string;                       // value from COLOR_OPTIONS constant
  clarity: string;                     // value from CLARITY_OPTIONS constant
  dimensions: string;
}

export interface BulkStonesFormData extends CollectionFormBase {
  collection_type: 'bulk_stones';
  stones: BulkStoneRow[];              // each row carries its own weight_unit
  description: string;
}

export interface JewelleryFormData extends CollectionFormBase {
  collection_type: 'jewellery';
  weight: number;
  weight_unit: string;
  description: string;
}

export interface IndustrialStonesFormData extends CollectionFormBase {
  collection_type: 'industrial_stones';
  stone_type: string;                  // value from INDUSTRIAL_STONE_TYPES constant
  variety: string;
  weight: number;
  weight_unit: string;                 // value from WEIGHT_UNITS constant
  description: string;
}

export type CollectionFormData =
  | SingleStoneFormData
  | BulkStonesFormData
  | JewelleryFormData
  | IndustrialStonesFormData;

/* ── Review Form Data ─────────────────────────────────────────────────────── */

export interface ReviewFormData {
  finalized_price: number;
  payment_method: PaymentMethod;
}

/* ── Grid / Listing ───────────────────────────────────────────────────────── */

export type SortField = 'collection_type' | 'asking_price' | 'created_at';
export type SortOrder = 'asc' | 'desc';

export interface SortConfig {
  field: SortField;
  order: SortOrder;
}

export interface CollectionFilterState {
  search: string;
  collection_type: string;  // '' = all types; or a CollectionType value
  status: string;           // '' = all statuses; 'review' | 'accepted'
}

/* ── API list response ────────────────────────────────────────────────────── */

export interface CollectionsResponse {
  data: CollectionRecord[];
  total: number;
  page: number;
  limit: number;
}

export interface CollectionsQueryParams {
  search: string;
  collection_type: string;
  status: string;            // '' = no filter; 'review' | 'accepted'
  created_at_from?: string;  // ISO date string, e.g. '2026-01-01' — backend provision, no UI yet
  created_at_to?: string;    // ISO date string, e.g. '2026-12-31' — backend provision, no UI yet
  created_by?: string;       // user UUID — backend provision, no UI yet
  sort_by: SortField;
  sort_order: SortOrder;
  page: number;
  limit: number;
}
