import type { Role } from '@/constants/roles';

/* ── Collection Type ──────────────────────────────────────────────────────── */

export type CollectionType = 'single_stone' | 'bulk_stones' | 'jewellery' | 'industrial_stones';

/* ── Seller (embedded in response) ───────────────────────────────────────── */

export interface SellerRef {
  id: string;
  first_name: string;
  last_name?: string;
  email: string;
  role: Role;
}
export interface SellerResponseRef {
 data: SellerRef[];
}

/* ── Bulk stone row ───────────────────────────────────────────────────────── */

export interface BulkStoneRow {
  gemstone_type: string;
  variety: string;
  quantity: number;
  weight: number;
  weight_unit: string;
}

/* ── Collection Records (API response shape) ──────────────────────────────── */

interface CollectionBase {
  id: string;
  serial_no: string;           // auto-generated by backend
  collection_type: CollectionType;
  seller_id: string;
  seller: SellerRef;           // embedded in GET responses
  certification_no: string;
  certification_lab: string;
  asking_price: number;
  image_urls: string[];        // backend-managed URLs
  created_at: string;
  updated_at: string;
}

export interface SingleStoneCollection extends CollectionBase {
  collection_type: 'single_stone';
  gemstone_type: string;
  variety: string;
  treatment: string;
  origin: string;
  weight: number;
  weight_unit: string;
  shape: string;
  cut: string;
  color: string;
  clarity: string;
  dimensions: string;
}

export interface BulkStonesCollection extends CollectionBase {
  collection_type: 'bulk_stones';
  stones: BulkStoneRow[];
  description: string;
}

export interface JewelleryCollection extends CollectionBase {
  collection_type: 'jewellery';
  weight: number;
  weight_unit: string;
  description: string;
}

export interface IndustrialStonesCollection extends CollectionBase {
  collection_type: 'industrial_stones';
  stone_type: string;
  variety: string;
  weight: number;
  weight_unit: string;
  description: string;
}

export type CollectionRecord =
  | SingleStoneCollection
  | BulkStonesCollection
  | JewelleryCollection
  | IndustrialStonesCollection;

/* ── Form Data (drawer state shape) ──────────────────────────────────────── */
// Values come from constants key-value pairs; submitted as their `value` string.
// images is File[] on the client; sent via a separate upload flow.

interface CollectionFormBase {
  collection_type: CollectionType;
  seller_id: string;
  certification_no: string;
  certification_lab: string;  // value from CERTIFICATION_LABS constant
  asking_price: number;
  images: File[];              // local preview; uploaded separately
}

export interface SingleStoneFormData extends CollectionFormBase {
  collection_type: 'single_stone';
  gemstone_type: string;       // value from GEMSTONE_TYPES constant
  variety: string;
  treatment: string;           // value from TREATMENT_OPTIONS constant
  origin: string;              // value from ORIGIN_OPTIONS constant
  weight: number;
  weight_unit: string;         // value from WEIGHT_UNITS constant
  shape: string;               // value from SHAPE_OPTIONS constant
  cut: string;                 // value from CUT_OPTIONS constant
  color: string;               // value from COLOR_OPTIONS constant
  clarity: string;             // value from CLARITY_OPTIONS constant
  dimensions: string;
  seller: SellerRef;             // selected seller object (for display in drawer); submitted as seller_id
}

export interface BulkStonesFormData extends CollectionFormBase {
  collection_type: 'bulk_stones';
  stones: BulkStoneRow[];      // each row carries its own weight_unit
  description: string;
  seller: SellerRef;             // selected seller object (for display in drawer); submitted as seller_id
}

export interface JewelleryFormData extends CollectionFormBase {
  collection_type: 'jewellery';
  weight: number;
  weight_unit: string;
  description: string;
  seller: SellerRef;             // selected seller object (for display in drawer); submitted as seller_id
}

export interface IndustrialStonesFormData extends CollectionFormBase {
  collection_type: 'industrial_stones';
  stone_type: string;          // value from INDUSTRIAL_STONE_TYPES constant
  variety: string;
  weight: number;
  weight_unit: string;         // value from WEIGHT_UNITS constant
  description: string;
  seller: SellerRef;             // selected seller object (for display in drawer); submitted as seller_id
}

export type CollectionFormData =
  | SingleStoneFormData
  | BulkStonesFormData
  | JewelleryFormData
  | IndustrialStonesFormData;

/* ── Grid / Listing ───────────────────────────────────────────────────────── */

export type SortField = 'collection_type' | 'asking_price' | 'created_at';
export type SortOrder = 'asc' | 'desc';

export interface SortConfig {
  field: SortField;
  order: SortOrder;
}

export interface CollectionFilterState {
  search: string;
  collection_type: string; // 'ALL' or a CollectionType value
}

/* ── API list response ────────────────────────────────────────────────────── */

export interface CollectionsResponse {
  data: CollectionRecord[];
  total: number;
  page: number;
  limit: number;
}

export interface CollectionsQueryParams {
  search: string;
  collection_type: string;
  sort_by: SortField;
  sort_order: SortOrder;
  page: number;
  limit: number;
}
